@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.sheathmagic.item.conceptcore;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;