@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.vanillamagic;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;