@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.sheathmagic;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;