@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.sheathmagic.crafting;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;