@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cn.nulladev.vanillamagic.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;