@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.sheathmagic.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;