@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package cn.nulladev.vanillamagic.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;